import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import NextAuthSessionProvider from "@/Providers/NextAuthSessionProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
})

export const metadata = {
  title: {
    default: "Learning NEXTJS",
    template: "%s | Learning NEXTJS"
  },
  description: "Generated by create next app",
  keywords: ['Next.js', 'React', 'JavaScript', "Learning"],
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <body
          className={`${poppins.className}  antialiased`}
        >
          <NavBar />
          {children}
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
